#!/usr/bin/env bash

set -xeuo pipefail

export PATH="/root/arch-ostree:$PATH"

disk="/dev/disk/by-id/ata-QEMU_HARDDISK_QM00002"
part_efi="/dev/disk/by-partlabel/efi"
part_boot="/dev/disk/by-partlabel/boot"
part_root="/dev/disk/by-partlabel/root"

cleanup() {
	umount -R /mnt || true
}

increase_cowspace() {
	mount -o remount,size=2G /run/archiso/cowspace
}

pacman_refresh() {
	pacman --noconfirm -Sy
}

prepare_disk() {
	sfdisk -w always "$disk" < "/root/arch-ostree/test/layout.sfdisk"
	sleep 1

	mkfs.vfat -F32 "$part_efi"
	mkfs.ext4 "$part_boot"
	mkfs.ext4 "$part_root"
}

mount_partitions() {
	mount "$part_root" /mnt

	mkdir -p /mnt/boot
	mount "$part_boot" /mnt/boot

	mkdir -p /mnt/boot/efi
	mount "$part_efi" /mnt/boot/efi
}

prepare_live_env() {
	arch-ostree prepare_live_env
}

setup_ostree() {
	ostree admin init-fs --sysroot /mnt --modern /mnt
	ostree admin stateroot-init --sysroot /mnt archlinux
	ostree config --repo /mnt/ostree/repo set sysroot.bootprefix 1
}

build_builder_container() {
	arch-ostree build_builder_container
}

build_rootfs() {
	arch-ostree \
		--pacman-cache /mnt/setup/pacman_cache \
		--rootfs-dir /mnt/setup/rootfs \
		build_rootfs_directory \
		/root/arch-ostree/test/build_rootfs.sh
}

commit_rootfs() {
	arch-ostree \
		--rootfs-dir /mnt/setup/rootfs \
		--ostree-repo /mnt/ostree/repo \
		commit_rootfs_directory \
		-- -v -b test
}

create_deployment_env() {
	rm -rf /mnt/setup/deployment
	ostree checkout \
		--repo /mnt/ostree/repo \
		--require-hardlinks \
		test /mnt/setup/deployment
}

deploy_cmd() {
	arch-ostree \
		--rootfs-dir /mnt/setup/deployment \
		--boot-dir /mnt/boot \
		--sysroot-dir /mnt \
		deploy_initial -- "$@"
}

grub_install() {
	deploy_cmd grub-install \
		--target x86_64-efi \
		--efi-directory /boot/efi \
		--bootloader-id=GRUB

	ln -sf ../loader/grub.cfg /mnt/boot/grub/grub.cfg
}

deploy() {
	rootuuid="$(blkid -o value -s UUID "$part_root")"
	deploy_cmd ostree admin deploy \
		--os=archlinux \
		--no-merge \
		--karg-none \
		--karg=root=UUID="$rootuuid" \
		--karg=rw \
		test
}

install_ssh_key() {
	install -d /mnt/ostree/deploy/archlinux/var/roothome/.ssh
	install \
		-m 0644 \
		"/tmp/id_rsa.pub" \
		/mnt/ostree/deploy/archlinux/var/roothome/.ssh/authorized_keys
}

write_fstab() {
	genfstab -U /mnt >> /mnt/ostree/deploy/archlinux/deploy/*/etc/fstab
}

host_shell() {
	bash
}

deploy_shell() {
	deploy_cmd "${args[@]}"
}

poweroff() {
	systemctl poweroff
}

group_prepare_existing() {
	cleanup
	increase_cowspace
	pacman_refresh
	mount_partitions
	prepare_live_env
}

tasks=(
	cleanup
	increase_cowspace
	pacman_refresh
	prepare_disk
	mount_partitions
	prepare_live_env
	setup_ostree
	build_builder_container
	build_rootfs
	commit_rootfs
	create_deployment_env
	grub_install
	deploy
	install_ssh_key
	write_fstab
)

if [ $# -ne 0 ]; then
	tasks=()

	for arg in "$@"; do
		shift

		if [ "$arg" = "--" ]; then
			break
		fi

		tasks+=("$arg")
	done

fi

args=("$@")

for task in "${tasks[@]}"; do
	"$task"
done
