#!/usr/bin/env bash

set -xeuo pipefail

export PATH="/root/arch-ostree:$PATH"

# shellcheck source=/lib/common.sh
source /root/arch-ostree/lib/common.sh

disk="/dev/disk/by-id/ata-QEMU_HARDDISK_QM00002"
supported_part_schemes=(
	plain
	lukspart
)
supported_boot_modes=(
	bios
	uefi
)
long_opts=(
	part-scheme:
)
part_scheme=plain
if [ -f /sys/firmware/efi/fw_platform_size ]; then
	boot_mode=uefi
else
	boot_mode=bios
fi
tasks=(
	cleanup
	increase_cowspace
	pacman_refresh
	prepare_disk
	mount
	prepare_live_env
	init_ostree
	build_builder_container
	build_rootfs
	commit_rootfs
	create_deployment_env
	grub_install
	deploy
	install_ssh_key
	write_fstab
)

task_cleanup() {
	umount -R /mnt || true
	cryptsetup close root || true
}

task_increase_cowspace() {
	mount -o remount,size=2G /run/archiso/cowspace
}

task_pacman_refresh() {
	pacman --noconfirm -Sy
}

task_prepare_disk() {
	sfdisk -w always "$disk" < "/root/arch-ostree/test/layout-$boot_mode.sfdisk"
	sleep 1

	if [ "$boot_mode" = "uefi" ]; then
		mkfs.vfat -F32 "$part_efi"
	fi
	mkfs.ext4 "$part_boot"

	case "$part_scheme" in
		plain)
			mkfs.ext4 "$part_root"
		;;
		lukspart)
			echo -n test | cryptsetup -v luksFormat "$part_root" -
			echo -n test | cryptsetup open "$part_root" root -d -
			mkfs.ext4 /dev/mapper/root
		;;
	esac
}

task_mount() {
	case "$part_scheme" in
		plain)
			mount "$part_root" /mnt
		;;
		lukspart)
			if [ ! -e /dev/mapper/root ]; then
				echo -n test | cryptsetup open "$part_root" root -d -
			fi

			mount /dev/mapper/root /mnt
		;;
	esac

	mkdir -p /mnt/boot
	mount "$part_boot" /mnt/boot

	if [ "$boot_mode" = "uefi" ]; then
		mkdir -p /mnt/efi
		mount "$part_efi" /mnt/efi
	fi
}

task_prepare_live_env() {
	arch-ostree prepare_live_env
}

task_init_ostree() {
	ostree admin init-fs --sysroot /mnt --modern /mnt
	ostree admin stateroot-init --sysroot /mnt archlinux
	ostree config --repo /mnt/ostree/repo set sysroot.bootprefix 1
}

task_build_builder_container() {
	arch-ostree build_builder_container
}

task_build_rootfs() {
	arch-ostree \
		--aur-dir /mnt/setup/aur \
		--pacman-cache /mnt/setup/pacman_cache \
		--rootfs-dir /mnt/setup/rootfs \
		build_rootfs_directory \
		/root/arch-ostree/test/build_rootfs.sh
}

task_commit_rootfs() {
	arch-ostree \
		--rootfs-dir /mnt/setup/rootfs \
		--ostree-repo /mnt/ostree/repo \
		commit_rootfs_directory \
		-- -v -b test
}

task_create_deployment_env() {
	rm -rf /mnt/setup/deployment
	ostree checkout \
		--repo /mnt/ostree/repo \
		--require-hardlinks \
		test /mnt/setup/deployment
}

deploy_cmd() {
	arch-ostree \
		--deploy-env-dir /mnt/setup/deployment \
		--sysroot-dir /mnt \
		deploy_env -- "$@"
}

task_grub_install() {
	case "$boot_mode" in
		bios)
			deploy_cmd grub-install --target i386-pc "$disk"
		;;
		uefi)
			deploy_cmd grub-install \
				--target x86_64-efi \
				--efi-directory /efi \
				--bootloader-id=GRUB
		;;
	esac

	ln -sf ../loader/grub.cfg /mnt/boot/grub/grub.cfg
}

task_deploy() {
	rootuuid="$(blkid -o value -s UUID "$part_root")"
	kargs=()

	case "$part_scheme" in
		plain)
			kargs+=(
				--karg=root=UUID="$rootuuid"
			)
		;;
		lukspart)
			kargs+=(
				--karg="rd.luks.name=$rootuuid=root"
				--karg=root=/dev/mapper/root
			)
		;;
	esac

	deploy_cmd ostree admin deploy \
		--os=archlinux \
		--no-merge \
		--karg-none \
		"${kargs[@]}" \
		--karg=rw \
		test
}

task_install_ssh_key() {
	install -d /mnt/ostree/deploy/archlinux/var/roothome/.ssh
	install \
		-m 0644 \
		"/tmp/id_rsa.pub" \
		/mnt/ostree/deploy/archlinux/var/roothome/.ssh/authorized_keys
}

task_write_fstab() {
	genfstab -U /mnt >> /mnt/ostree/deploy/archlinux/deploy/*/etc/fstab
}

task_host_shell() {
	bash
}

task_deploy_shell() {
	deploy_cmd "${args[@]}"
}

task_poweroff() {
	systemctl poweroff
}

task_group_prepare_existing() {
	task_cleanup
	task_increase_cowspace
	task_pacman_refresh
	task_mount
	task_prepare_live_env
}

if ! temp=$(getopt -o '+' --long "$(join_by , "${long_opts[@]}")" -- "$@"); then
	die "Invalid arguments"
fi

eval set -- "$temp"
while true; do
	case "$1" in
		'--part-scheme')
			name="$(arg_to_varname "$1")"
			printf -v "$name" "%s" "$2"
			shift 2
			continue
		;;
		'--')
			shift
			break
		;;
		*)
			die "BUG: Unexpected argument: $1"
		;;
	esac
done

if [ $# -ne 0 ]; then
	tasks=()

	for arg in "$@"; do
		shift

		if [ "$arg" = "--" ]; then
			break
		fi

		tasks+=("$arg")
	done
fi

args=("$@")

for task in "${tasks[@]}"; do
	if ! have_function "task_$task"; then
		die "Unsupported task: $task"
	fi
done

if [[ ! ${supported_part_schemes[*]} =~ $part_scheme ]]; then
	die "Unsupported partition scheme: $part_scheme"
fi

if [[ ! ${supported_boot_modes[*]} =~ $boot_mode ]]; then
	die "Unsupported boot_mode: $boot_mode"
fi

case "$boot_mode" in
	bios)
		part_boot="$disk-part1"
		part_root="$disk-part2"
	;;
	uefi)
		part_efi="/dev/disk/by-partlabel/efi"
		part_boot="/dev/disk/by-partlabel/boot"
		part_root="/dev/disk/by-partlabel/root"
	;;
esac

for task in "${tasks[@]}"; do
	"task_$task"
done
