#!/usr/bin/env bash

set -euo pipefail

script=$(readlink -f "$0")
gitdir=$(dirname "$script")

pacstrap_tag="archlinux-pacstrap"
rootfs_tag="archlinux-ostree-base"
rootfs_containerfile="$gitdir/Containerfile.base"
rootfs_dir="$PWD/rootfs"
ostree_repo="/sysroot/ostree/repo"
podman_build_cache=false

# shellcheck disable=SC2059 # $1 and $2 can contain the printf modifiers
out() { printf "$1 $2\n" "${@:3}"; }
error() { out "====> ERROR:" "$@"; } >&2
warning() { out "====> WARNING:" "$@"; } >&2
msg() { out "====>" "$@"; }
die() { error "$@"; exit 1; }

arg_to_varname() {
	name="${1:2}"
	echo "${name//-/_}"
}

usage() {
  cat <<EOF
usage: ${0##*/} [options] [command] [arg...]

  <bool> is a value of 0, false, no, 1, true or yes.
  \$gitdir: $gitdir
  \$PWD: $PWD

  Options:
    --boot-dir <path>              Path to the mounted boot directory.
    --podman-build-cache <bool>    Enable/Disable podman build cache. Boolean.
                                   Default: no.
    --pacman-cache <path>          Path to a persistent pacman package cache.
                                   Default: undefined, thus the pacman cache
                                   is disabled.
    --pacstrap-tag <name>          Name of the tag to use for the pacstrap
                                   container.
                                   Default: archlinux-pacstrap.
    --rootfs-tag <name>            Name of the tag to use for the rootfs
                                   container.
                                   Default: archlinux-ostree-base.
    --rootfs-containerfile <path>  Path to the Containerfile used for building
                                   the rootfs container.
                                   Default: \$git_dir/Containerfile.base.
    --rootfs-dir <path>            Path to the directory where the rootfs will
                                   be created in.
                                   Default: \$PWD/rootfs.
    --ostree-repo <path>           Path to the ostree repository.
                                   Default: /sysroot/ostree/repo.

    --help                         Print this help message

  Commands:
    build_pacstrap_container         (Re-)Build pacstrap container that's used
                                     by the other commands and tag it with
				     --pacstrap-tag.
    build_rootfs_container           Build rootfs container from
                                     --rootfs-containerfile and tag it with
                                     --rootfs-tag.
    enter_rootfs_container [arg...]  Enter --rootfs-tag container. All changes
                                     will be lost.
    commit_rootfs_container [arg...] Commit --rootfs-tag container to
                                     --ostree-repo. This tool provides --repo
                                     and --tree-dir to ostree commit.
                                     Everything else (like branch name) can and
                                     has to be provided by you.
    pacstrap_rootfs_directory [pkg...] Run pacstrap on --rootfs-dir. If the
                                       directory exists, it will NOT be deleted.
				       [pkg...] will be passed to packstrap and
				       must contain the packages that shall be
				       installed.
    enter_rootfs_directory [arg...]  Enter --rootfs-dir. All changes will be
                                     lost.
    commit_rootfs_directory [arg...] Commit --rootfs-dir container to
                                     --ostree-repo. This tool provides --repo
                                     and --tree-dir to ostree commit.
                                     Everything else (like branch name) can and
                                     has to be provided by you.

EOF
}

long_opts='boot-dir:,podman-build-cache:,pacman-cache:,pacstrap-tag:,rootfs-tag:,rootfs-containerfile:,rootfs-dir:,ostree-repo:,sysroot-dir:,help'
if ! temp=$(getopt -o '' --long "$long_opts" -- "$@"); then
	die "Invalid arguments"
fi

eval set -- "$temp"
while true; do
	case "$1" in
		'--boot-dir'|\
		'--pacman-cache'|\
		'--pacstrap-tag'|\
		'--rootfs-tag'|\
		'--rootfs-container'|\
		'--rootfs-dir'|\
		'--ostree-repo'|\
		'--sysroot-dir')
			name="$(arg_to_varname "$1")"
			printf -v "$name" "%s" "$2"
			shift 2
			continue
		;;
		'--podman-build-cache')
			name="$(arg_to_varname "$1")"

			case "$2" in
				'true'|'1'|'yes')
					eval "$name=true"
				;;
				'false'|'0'|'no')
					eval "$name=false"
				;;
				*)
					die "Unsupported bool value: $2"
				;;
			esac

			shift 2
			continue
		;;
		'--help')
			usage
			exit $(( $# ? 0 : 1 ))
		;;
		'--')
			shift
			break
		;;
		*)
			die "BUG: Unexpected argument: $1"
		;;
	esac
done

if [ -z ${1+x} ]; then
	die "Missing command argument"
fi
command="${1}"
shift 1

pacman_cache_args=()
# shellcheck disable=SC2236 # This doesn't work with -n
if [ ! -z ${pacman_cache+x} ]; then
	mkdir -p "$pacman_cache"
	pacman_cache_args=(
		-v "$(realpath "$pacman_cache"):/var/cache/pacman/pkg"
	)
fi

podman_build_cache_args=()
if [ "$podman_build_cache" = false ]; then
	podman_build_cache_args+=(--no-cache)
fi

case "$command" in
	'prepare_live_env')
		msg "Install required packages"
		pacman \
			--needed \
			--noconfirm \
			-Sy \
			fuse-overlayfs \
			git \
			ostree \
			podman

		msg "Patch storage.conf"
		sed -i \
		    -e 's|^\(graphroot\s*=\s*\).*|\1"/mnt/setup/container-storage"|g' \
		    /etc/containers/storage.conf

		msg "Patch containers.conf"
		sed -i \
		    -e 's|^# \(image_copy_tmp_dir\s*=\s*\).*|\1"/mnt/setup/container-tmp"|g' \
		    /etc/containers/containers.conf
		mkdir -p "/mnt/setup/container-tmp"
	;;
	'build_pacstrap_container')
		podman build \
			"${podman_build_cache_args[@]}" \
			-f "$gitdir/Containerfile.pacstrap" \
			-t "$pacstrap_tag"
	;;

	'build_rootfs_container')
		podman build \
			"${podman_build_cache_args[@]}" \
			"${pacman_cache_args[@]}" \
			--cap-add sys_admin \
			--cap-add mknod \
			-f "$rootfs_containerfile" \
			-t "$rootfs_tag"
	;;
	'enter_rootfs_container')
		podman run \
			--rm -it \
			"localhost/$rootfs_tag" \
			"$@"
	;;
	'commit_rootfs_container')
		podman run \
			--cap-add sys_admin \
			--security-opt apparmor=unconfined \
			--mount "type=image,src=localhost/$rootfs_tag,dst=/mnt-lower" \
			--mount "type=bind,src=$ostree_repo,dst=/sysroot/ostree/repo" \
			-v "$PWD:/opt:ro" \
			--rm -it \
			"localhost/$pacstrap_tag" \
			/opt/commit_rootfs "$@"
	;;

	'pacstrap_rootfs_directory')
		if [ -d "$rootfs_dir" ]; then
			warning "rootfs directory exists already."
		else
			mkdir -p "$rootfs_dir"
		fi

		podman run \
			--cap-add sys_admin \
			--cap-add mknod \
			--security-opt apparmor=unconfined \
			"${pacman_cache_args[@]}" \
			-v "$rootfs_dir:/mnt" \
			--rm -it \
			"localhost/$pacstrap_tag" \
			pacstrap -c -G -M /mnt "$@"
	;;
	'enter_rootfs_directory')
		podman run \
			--rm -it \
			--rootfs "$rootfs_dir:O" \
			/bin/bash "$@"
	;;
	'commit_rootfs_directory')
		podman run \
			--cap-add sys_admin \
			--security-opt apparmor=unconfined \
			--mount "type=bind,src=$rootfs_dir,dst=/mnt-lower,ro" \
			--mount "type=bind,src=$ostree_repo,dst=/sysroot/ostree/repo" \
			-v "$PWD:/opt:ro" \
			--tmpfs /overlay \
			--rm -it \
			"localhost/$pacstrap_tag" \
			/opt/commit_rootfs "$@"
	;;
	'deploy')
		podman run \
			--privileged \
			--security-opt apparmor=unconfined \
			--security-opt seccomp=unconfined \
			--security-opt label=disable \
			--security-opt unmask=ALL \
			--rm -it \
			-v "/sys:/sys:rbind" \
			-v "$boot_dir:/boot:rbind" \
			-v "$sysroot_dir:/sysroot:rbind" \
			"localhost/$pacstrap_tag" \
			/bin/bash
			# ostree admin deploy "$@"
	;;
        'deploy2')
		unshare -m "$gitdir/initial_deployment_env" "$rootfs_dir" "$boot_dir" "$sysroot_dir"
        ;;
	*)
		die "Unsupported command: ${command}"
	;;
esac

msg "Successful"
