#!/bin/bash

set -euo pipefail

script=$(readlink -f "$0")
gitdir=$(dirname "$script")
outdir="$gitdir/out"
pkgcache="$outdir/pkgcache"
rootfs="$outdir/rootfs"
iidfile="$outdir/builder.iid"
pkgcache_patched="$outdir/pkgcache-patched"
args=("$@")
commit=0
clean_rootfs=0
extra_build_args=()

if [ ${#args[@]} -eq 0 ]; then
    args=(./scripts/makeroot)
    commit=1
    clean_rootfs=1
fi

if [ "${FORCE_BUILDER_REBUILD:-}" == "1" ]; then
    extra_build_args+=(--no-cache)
fi

mkdir -p "$outdir"
mkdir -p "$pkgcache"
mkdir -p "$pkgcache_patched"

if [ -d "$rootfs" ] && [ $clean_rootfs -eq 1 ]; then
    rm -rf "$rootfs"
fi
mkdir -p "$rootfs"

podman build -f Containerfile.builder --iidfile "$iidfile" "${extra_build_args[@]}"
iid=$(cat "$iidfile")

podman run --rm --init -it \
    --userns auto \
    --net host \
    --security-opt label=disable \
    --cap-add all \
    -v "$gitdir:$gitdir:ro" \
    -v "$outdir:$outdir:idmap" \
    -v "$pkgcache:/var/cache/pacman/pkg:idmap" \
    -w "$gitdir" \
    -e "OUTDIR=$outdir" \
    -e "ARCH_ROOTFS=$rootfs" \
    -e "PKGCACHE_PATCHED=$pkgcache_patched" \
    "$iid" \
    "${args[@]}"

if [ $commit -eq 1 ]; then
    ostree commit -v -b archlinux/latest --tree=dir="$rootfs"
fi
