#!/bin/bash

source+=(
	https://raw.githubusercontent.com/hyprwm/Hyprland/main/nix/patches/wlroots-hidpi.patch
	revert.patch
)
sha256sums+=(
	a129e2aadd91b6c6c7e7394f0de5a412042ad75ad1f826af14e4ea085d79285e
	SKIP
)

test -n "$(declare -f prepare)"
eval "${_/prepare/prepare_orig}"

cp "$patcher_gitdir/package_patchers/0001-Revert-compositor-send-WL_SURFACE_ERROR_INVALID_SIZE.patch" revert.patch

prepare() {
	prepare_orig "$@"

	echo "$PWD"
	pushd subprojects/wlroots
	patch -Np1 -i "${srcdir}/wlroots-hidpi.patch"
	patch -Np1 -i "${srcdir}/revert.patch"
	popd
}
