#!/bin/bash

set -xeuo pipefail

pkgcache_patched="$PKGCACHE_PATCHED"
package_filename="$PACKAGE_NAME-$PACKAGE_VERSION-x86_64.pkg.tar.zst"
pkgfile_cached="$pkgcache_patched/$package_filename"
gitdir="$PWD"

if [ -e "$pkgfile_cached" ]; then
	echo "Package already built" >&2
	exit 0
fi

pushd ~/

if [ -e "$PACKAGE_NAME" ]; then
	rm -rf "$PACKAGE_NAME"
fi

pkgctl repo clone --protocol=https --switch="$PACKAGE_VERSION" "$PACKAGE_NAME"
cd "$PACKAGE_NAME"

echo "groups+=(modified); patcher_gitdir=\"$gitdir\"; source \"$gitdir/package_patchers/$PACKAGE_NAME\"" >> PKGBUILD

makepkg --noconfirm -s

sudo cp "$package_filename" "$pkgfile_cached"
